-- For posts which are tagged with only ‘python’ or ‘dbt’
-- , what is the year over year change
-- of question-to-answer ratio for the last 10 years? How about the rate of approved
-- answers on questions for the same time period? How do posts tagged with only ‘python’
-- compare to posts only tagged with ‘dbt’?